version: "3.4"

services:
  ros-rviz:
    build:
        context: .
        dockerfile: Dockerfile
    image: rviz_container:noetic
    container_name: rviz_test
    network_mode: "host"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    privileged: true
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw